[package]
name = "termcity-app"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "termcity-rs"
path = "src/main.rs"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.30.2"
termcity-core = { path = "../termcity-core" }

[dev-dependencies]
termcity-test-support = { path = "../termcity-test-support" }

[lints]
workspace = true
